{
    "version": "1.0.0",
    "title": "System is resilient to provider's failures",
    "description": "Can our consumer survive gracefully a provider's failure?",
    "tags": [
        "service",
        "cloudfoundry",
        "spring"
    ],
    "chaosiq": {
        "init_ref": "50da1c5a-923f-4bc6-9239-126c97755571",
        "suggested_experiment_ref": "80cee425-9163-4318-8b32-6e561af18258",
        "target": "cloud-foundry"
    },
    "configuration": {
        "cf_api_url": "https://api.local.pcfdev.io",
        "cf_verify_ssl": false
    },
    "secrets": {
        "cloudfoundry": {
            "cf_password": "pass",
            "cf_username": "user"
        }
    },
    "steady-state-hypothesis": {
        "probes": [
            {
                "name": "consumer-service-must-still-respond",
                "provider": {
                    "type": "http",
                    "url": "http://simple-boot-feign-direct-microservice-consumer.local.pcfdev.io/invokeConsumedService"
                },
                "tolerance": 200,
                "type": "probe"
            }
        ],
        "title": "System is healthy"
    },
    "method": [
        {
            "name": "delete_app",
            "provider": {
                "arguments": {
                    "app_name": "simple-spring-boot-provider",
                    "org_name": "pcfdev-org",
                    "space_name": "pcfdev-space"
                },
                "func": "delete_app",
                "module": "chaoscf.actions",
                "secrets": [
                    "cloudfoundry"
                ],
                "type": "python"
            },
            "type": "action"
        }
    ],
    "rollbacks": []
}